# 
default: fem2d.pdf fem2d.info

fem2d.pdf:  fem2d.texi
	texi2pdf fem2d.texi

fem2d.info:  fem2d.texi
	makeinfo fem2d.texi

clean:
	rm fem2d.aux fem2d.fn fem2d.log fem2d.tp fem2d.cp fem2d.fns fem2d.pdf fem2d.vr fem2d.cps fem2d.ky fem2d.pg fem2d.toc fem2d.info
