#
default:
	cd fem2d; make
	cd lin2d; make
	cd nln2d; make
	cd post2d; make
	cd equ2d; make
	cd opt2d; make
	cd rem2d; make

clean:
	cd fem2d; make clean
	cd lin2d; make clean
	cd nln2d; make clean
	cd post2d; make clean
	cd equ2d; make clean
	cd opt2d; make clean
	cd rem2d; make clean
	rm hash/hash
